version: '2'
services:

  nginx:
    image: nginx:1-alpine
    ports:
      - 8089:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    restart: always

  backend:
    image: over-engineered-calculator-backend
    build: backend
    ports:
      - '8080:8080'
    restart: always
    environment:
      - GIN_MODE=${GIN_MODE}

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=over-engineered-calculator
    ports:
      - '5432:5432'
    volumes: 
      - ./db/db-init.sql:/docker-entrypoint-initdb.d/db.sql
      - ./db/data:/var/lib/postgresql/data

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    command: --base /dozzle
    

      