package errorid

var EMPTY_INPUT_ERROR string = "EMPTY_INPUT_ERROR"
var CURSOR_PARSING_ERROR string = "CURSOR_PARSING_ERROR"
var SESSION_ID_VALIDATION_ERROR = "SESSION_ID_VALIDATION_ERROR"

var PARSING_ERROR string = "PARSING_ERROR"
var LEXING_ERROR string = "LEXING_ERROR"

var PARSING_OR_LEXING_PANIC_ERROR = "PARSING_OR_LEXING_PANIC_ERROR"
var DIVISION_BY_ZERO_ERROR string = "DIVISION_BY_ZERO_ERROR"

var HISTORY_FETCH_ERROR = "HISTORY_FETCH_ERROR"
var HISTORY_SCAN_ROW_ERROR = "HISTORY_SCAN_ROW_ERROR"
var HISTORY_CURSOR_ERROR = "HISTORY_CURSOR_ERROR"
var INSERT_CALCULATION_ERROR = "INSERT_CALCULATION_ERROR"
